/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i0rpF9OTArQ
 */
import { useEffect, useState } from "react"
import AssignmentCard from "@/shad/assignment-card"
import AssignmentHeader from "@/shad/assignment-header"
import AssignmentFilter from "@/shad/assignment-filter"
import { api } from "@/utils/api"
import Loader from "@/images/loader"

export function AssignmentList() {
  const [assignmentSearch, setAssignmentSearch] = useState("")
  const getAssignments = api.dbOperations.getAssignments.useQuery(undefined, { enabled: false, })
  useEffect(() => {
    getAssignments.refetch()
  }, [])
  return (
    <div key="1" className="flex flex-col h-screen bg-dark-100">
      <AssignmentHeader />
      <main className="flex flex-1 flex-col gap-4 py-4 md:gap-8 md:p-10 dark:bg-gray-900">
        <AssignmentFilter setAssignmentSearch={setAssignmentSearch} />
        <div className="flex w-full flex-col gap-6 w-full px-32 text-white items-center">
          <Assignments />
        </div>
      </main>
    </div>
  )
}

function Assignments() {
  const getAssignments = api.dbOperations.getAssignments.useQuery(undefined, { enabled: false, })
  if (getAssignments.isLoading) {
    return <Loader />
  }
  if (getAssignments.isError) {
    return <div>{getAssignments.error.message}</div>
  }
  if (getAssignments.data && getAssignments.data.length === 0) {
    return <div>No assignments found.</div>
  }
  return (
    <>
      {getAssignments.data.map((assignment) => {
        return <AssignmentCard key={assignment.id} assignmentName={assignment.name} assignmentDescription={assignment.id} assignmentDate={assignment.createdAt.getDate.toString()} />
      })}
    </>
  )
}